/* ============================================
   HARVEST HUB — crop_names.js
   Crop name translations: Telugu, Hindi, Tamil, Kannada
   (English falls back to the key itself)
   ============================================ */
const CROP_NAMES = {
    en: {},  // Falls back to English key
    te: {
        'Amaranth Leaves': 'తోటకూర ఆకులు', 'Amla': 'ఉసిరి', 'Ash Gourd': 'బూడిద గుమ్మడి',
        'Baby Corn': 'బేబీ కార్న్', 'Banana Flower': 'అరటి పూవు', 'Beetroot': 'దుంపలు',
        'Bell Pepper (Capsicum)': 'క్యాప్సికం', 'Bitter Gourd': 'కాకరకాయ', 'Bottle Gourd': 'సొరకాయ',
        'Butter Beans': 'వెన్న చిక్కుళ్ళు', 'Broad Beans (Fava / Lima)': 'అనుమతి చిక్కుళ్ళు',
        'Cabbage': 'క్యాబేజీ', 'Carrot': 'క్యారెట్', 'Cauliflower': 'కాలీఫ్లవర్',
        'Cluster Beans': 'గోరుచిక్కుళ్ళు', 'Coconut (Fresh)': 'కొబ్బరి (తాజా)',
        'Coriander Leaves (Cilantro)': 'కొత్తిమీర', 'Corn': 'మొక్కజొన్న',
        'Cucumber': 'దోసకాయ', 'Curry Leaves': 'కరివేపాకు', 'Dill Leaves': 'సోపు ఆకులు',
        'Drumsticks': 'మునగకాయ', 'Eggplant (Brinjal)': 'వంకాయ', 'Brinjal (Big)': 'పెద్ద వంకాయ',
        'Elephant Yam': 'కొండ దుంప', 'Fenugreek Leaves': 'మెంతి ఆకులు',
        'French Beans (Green Beans)': 'బీన్స్', 'Garlic': 'వెల్లుల్లి', 'Ginger': 'అల్లం',
        'Green Chili': 'పచ్చి మిరప', 'Green Peas': 'పచ్చి బఠానీలు', 'Ivy Gourd': 'దొండ',
        'Lemon (Lime)': 'నిమ్మకాయ', 'Mango': 'మామిడి', 'Mint Leaves': 'పుదీనా',
        'Mushroom': 'పుట్టగొడుగు', 'Mustard Leaves': 'ఆవాల ఆకులు', 'Okra (Ladies Finger)': 'బెండకాయ',
        'Onion (Big)': 'ఉల్లి (పెద్ద)', 'Onion (Small)': 'ఉల్లి (చిన్న)', 'Potato': 'బంగాళాదుంప',
        'Pumpkin': 'గుమ్మడికాయ', 'Radish (Daikon)': 'మూలంగ', 'Ridge Gourd': 'బీరకాయ',
        'Snake Gourd': 'పొట్లకాయ', 'Sorrel Leaves': 'గోంగూర', 'Spinach': 'పాలకూర',
        'Sweet Potato': 'చిలగడ దుంప', 'Tomato': 'టమాటా',
        'Paddy (Rice)': 'వరి (ధాన్యం)', 'Wheat': 'గోధుమ', 'Bajra (Pearl Millet)': 'సజ్జ',
        'Jowar (Sorghum)': 'జొన్న', 'Sugarcane': 'చెరకు', 'Cotton': 'పత్తి (గింజ)',
        'Turmeric': 'పసుపు', 'Dry Chilli': 'ఎండు మిర్చి', 'Groundnut (Peanut)': 'వేరుశనగ',
        'Soybean': 'సోయా', 'Sunflower': 'పొద్దుతిరుగుడు', 'Black Gram (Urad)': 'మినుములు',
        'Bengal Gram (Chana)': 'శనగలు', 'Red Gram (Tur Dal)': 'కంది పప్పు', 'Green Gram (Moong)': 'పెసలు',
    },
    hi: {
        'Amaranth Leaves': 'चौलाई के पत्ते', 'Amla': 'आंवला', 'Ash Gourd': 'पेठा',
        'Baby Corn': 'बेबी कॉर्न', 'Banana Flower': 'केले का फूल', 'Beetroot': 'चुकंदर',
        'Bell Pepper (Capsicum)': 'शिमला मिर्च', 'Bitter Gourd': 'करेला', 'Bottle Gourd': 'लौकी',
        'Butter Beans': 'मक्खन सेम', 'Broad Beans (Fava / Lima)': 'बाकला',
        'Cabbage': 'पत्तागोभी', 'Carrot': 'गाजर', 'Cauliflower': 'फूलगोभी',
        'Cluster Beans': 'ग्वारफली', 'Coconut (Fresh)': 'नारियल (ताजा)',
        'Coriander Leaves (Cilantro)': 'हरा धनिया', 'Corn': 'मक्का',
        'Cucumber': 'खीरा', 'Curry Leaves': 'कड़ी पत्ता', 'Dill Leaves': 'सोआ पत्ती',
        'Drumsticks': 'सहजन', 'Eggplant (Brinjal)': 'बैंगन', 'Brinjal (Big)': 'बड़ा बैंगन',
        'Elephant Yam': 'सूरन', 'Fenugreek Leaves': 'मेथी पत्ती',
        'French Beans (Green Beans)': 'फ्रेंच बीन्स', 'Garlic': 'लहसुन', 'Ginger': 'अदरक',
        'Green Chili': 'हरी मिर्च', 'Green Peas': 'हरे मटर', 'Ivy Gourd': 'कुंदरू',
        'Lemon (Lime)': 'नींबू', 'Mango': 'आम', 'Mint Leaves': 'पुदीना',
        'Mushroom': 'मशरूम', 'Mustard Leaves': 'सरसों पत्ता', 'Okra (Ladies Finger)': 'भिंडी',
        'Onion (Big)': 'प्याज (बड़ा)', 'Onion (Small)': 'प्याज (छोटा)', 'Potato': 'आलू',
        'Pumpkin': 'कद्दू', 'Radish (Daikon)': 'मूली', 'Ridge Gourd': 'तोरई',
        'Snake Gourd': 'चिचिंडा', 'Sorrel Leaves': 'खट्टी सोरेल', 'Spinach': 'पालक',
        'Sweet Potato': 'शकरकंद', 'Tomato': 'टमाटर',
        'Paddy (Rice)': 'धान (चावल)', 'Wheat': 'गेहूँ', 'Bajra (Pearl Millet)': 'बाजरा',
        'Jowar (Sorghum)': 'ज्वार', 'Sugarcane': 'गन्ना', 'Cotton': 'कपास (बीज)',
        'Turmeric': 'हल्दी', 'Dry Chilli': 'सूखी मिर्च', 'Groundnut (Peanut)': 'मूँगफली',
        'Soybean': 'सोयाबीन', 'Sunflower': 'सूरजमुखी', 'Black Gram (Urad)': 'उड़द दाल',
        'Bengal Gram (Chana)': 'चना दाल', 'Red Gram (Tur Dal)': 'अरहर दाल', 'Green Gram (Moong)': 'मूँग दाल',
    },
    ta: {
        'Amaranth Leaves': 'முளைக்கீரை', 'Amla': 'நெல்லிக்காய்', 'Ash Gourd': 'வெண்பூசணி',
        'Baby Corn': 'பேபி கார்ன்', 'Banana Flower': 'வாழை பூ', 'Beetroot': 'பீட்ரூட்',
        'Bell Pepper (Capsicum)': 'குடை மிளகாய்', 'Bitter Gourd': 'பாகற்காய்', 'Bottle Gourd': 'சுரைக்காய்',
        'Butter Beans': 'மணத்தக்காளி', 'Broad Beans (Fava / Lima)': 'அவரைக்காய்',
        'Cabbage': 'முட்டைகோஸ்', 'Carrot': 'கேரட்', 'Cauliflower': 'காலிஃப்ளவர்',
        'Cluster Beans': 'கொத்தவரங்காய்', 'Coconut (Fresh)': 'தேங்காய் (பச்சை)',
        'Coriander Leaves (Cilantro)': 'கொத்தமல்லி', 'Corn': 'மக்காச்சோளம்',
        'Cucumber': 'வெள்ளரிக்காய்', 'Curry Leaves': 'கறிவேப்பிலை', 'Dill Leaves': 'சோம்பு இலை',
        'Drumsticks': 'முருங்கைக்காய்', 'Eggplant (Brinjal)': 'கத்திரிக்காய்', 'Brinjal (Big)': 'பெரிய கத்திரி',
        'Elephant Yam': 'சேனைக்கிழங்கு', 'Fenugreek Leaves': 'வெந்தய கீரை',
        'French Beans (Green Beans)': 'பீன்ஸ்', 'Garlic': 'பூண்டு', 'Ginger': 'இஞ்சி',
        'Green Chili': 'பச்சை மிளகாய்', 'Green Peas': 'பச்சைப் பட்டாணி', 'Ivy Gourd': 'கோவைக்காய்',
        'Lemon (Lime)': 'எலுமிச்சை', 'Mango': 'மாம்பழம்', 'Mint Leaves': 'புதினா',
        'Mushroom': 'காளான்', 'Mustard Leaves': 'கடுகு கீரை', 'Okra (Ladies Finger)': 'வெண்டைக்காய்',
        'Onion (Big)': 'வெங்காயம் (பெரிய)', 'Onion (Small)': 'வெங்காயம் (சிறிய)', 'Potato': 'உருளைக்கிழங்கு',
        'Pumpkin': 'பரங்கிக்காய்', 'Radish (Daikon)': 'முள்ளங்கி', 'Ridge Gourd': 'பீர்க்கங்காய்',
        'Snake Gourd': 'புடலங்காய்', 'Sorrel Leaves': 'புளிச்ச கீரை', 'Spinach': 'பசலைக்கீரை',
        'Sweet Potato': 'சர்க்கரைவள்ளிக்கிழங்கு', 'Tomato': 'தக்காளி',
        'Paddy (Rice)': 'நெல் (அரிசி)', 'Wheat': 'கோதுமை', 'Bajra (Pearl Millet)': 'கம்பு',
        'Jowar (Sorghum)': 'சோளம்', 'Sugarcane': 'கரும்பு', 'Cotton': 'பருத்தி (விதை)',
        'Turmeric': 'மஞ்சள்', 'Dry Chilli': 'காய்ந்த மிளகாய்', 'Groundnut (Peanut)': 'வேர்க்கடலை',
        'Soybean': 'சோயா பீன்', 'Sunflower': 'சூரியகாந்தி', 'Black Gram (Urad)': 'உளுத்தம் பருப்பு',
        'Bengal Gram (Chana)': 'கடலைப்பருப்பு', 'Red Gram (Tur Dal)': 'தூவரம் பருப்பு', 'Green Gram (Moong)': 'பாசிப்பருப்பு',
    },
    kn: {
        'Amaranth Leaves': 'ಹರಿವೆ ಸೊಪ್ಪು', 'Amla': 'ನೆಲ್ಲಿಕಾಯಿ', 'Ash Gourd': 'ಬೂದು ಕುಂಬಳ',
        'Baby Corn': 'ಬೇಬಿ ಕಾರ್ನ್', 'Banana Flower': 'ಬಾಳೆ ಹೂ', 'Beetroot': 'ಬೀಟ್‌ರೂಟ್',
        'Bell Pepper (Capsicum)': 'ಕ್ಯಾಪ್ಸಿಕಮ್', 'Bitter Gourd': 'ಹಾಗಲಕಾಯಿ', 'Bottle Gourd': 'ಸೋರೆಕಾಯಿ',
        'Butter Beans': 'ಬೆಣ್ಣೆ ಬೀನ್ಸ್', 'Broad Beans (Fava / Lima)': 'ಹುರಳಿಕಾಳು',
        'Cabbage': 'ಎಲೆಕೋಸು', 'Carrot': 'ಗಜ್ಜರಿ', 'Cauliflower': 'ಹೂಕೋಸು',
        'Cluster Beans': 'ಗೋರಿಕಾಯಿ', 'Coconut (Fresh)': 'ತೆಂಗಿನಕಾಯಿ (ತಾಜಾ)',
        'Coriander Leaves (Cilantro)': 'ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು', 'Corn': 'ಮೆಕ್ಕೆಜೋಳ',
        'Cucumber': 'ಸೌತೆಕಾಯಿ', 'Curry Leaves': 'ಕರಿಬೇವು', 'Dill Leaves': 'ಸಬ್ಸಿಗೆ ಸೊಪ್ಪು',
        'Drumsticks': 'ನುಗ್ಗೆಕಾಯಿ', 'Eggplant (Brinjal)': 'ಬದನೆಕಾಯಿ', 'Brinjal (Big)': 'ದೊಡ್ಡ ಬದನೆ',
        'Elephant Yam': 'ಸೇನೆ ದುಂಡ', 'Fenugreek Leaves': 'ಮೆಂತ್ಯ ಸೊಪ್ಪು',
        'French Beans (Green Beans)': 'ಫ್ರೆಂಚ್ ಬೀನ್ಸ್', 'Garlic': 'ಬೆಳ್ಳುಳ್ಳಿ', 'Ginger': 'ಶುಂಠಿ',
        'Green Chili': 'ಹಸಿ ಮೆಣಸಿನಕಾಯಿ', 'Green Peas': 'ಹಸಿ ಬಟಾಣಿ', 'Ivy Gourd': 'ತೊಂಡೆಕಾಯಿ',
        'Lemon (Lime)': 'ನಿಂಬೆಹಣ್ಣು', 'Mango': 'ಮಾವಿನಹಣ್ಣು', 'Mint Leaves': 'ಪುದೀನಾ',
        'Mushroom': 'ಅಣಬೆ', 'Mustard Leaves': 'ಸಾಸಿವೆ ಸೊಪ್ಪು', 'Okra (Ladies Finger)': 'ಬೆಂಡೆಕಾಯಿ',
        'Onion (Big)': 'ಈರುಳ್ಳಿ (ದೊಡ್ಡ)', 'Onion (Small)': 'ಈರುಳ್ಳಿ (ಚಿಕ್ಕ)', 'Potato': 'ಆಲೂಗಡ್ಡೆ',
        'Pumpkin': 'ಕುಂಬಳಕಾಯಿ', 'Radish (Daikon)': 'ಮೂಲಂಗಿ', 'Ridge Gourd': 'ಹೀರೇಕಾಯಿ',
        'Snake Gourd': 'ಪಡವಲಕಾಯಿ', 'Sorrel Leaves': 'ಗೊಂಗೂರ', 'Spinach': 'ಪಾಲಕ್',
        'Sweet Potato': 'ಸಿಹಿ ಗೆಣಸು', 'Tomato': 'ಟೊಮ್ಯಾಟೋ',
        'Paddy (Rice)': 'ಭತ್ತ (ಅಕ್ಕಿ)', 'Wheat': 'ಗೋಧಿ', 'Bajra (Pearl Millet)': 'ಸಜ್ಜೆ',
        'Jowar (Sorghum)': 'ಜೋಳ', 'Sugarcane': 'ಕಬ್ಬು', 'Cotton': 'ಹತ್ತಿ (ಬೀಜ)',
        'Turmeric': 'ಅರಿಶಿನ', 'Dry Chilli': 'ಒಣ ಮೆಣಸಿನಕಾಯಿ', 'Groundnut (Peanut)': 'ಕಡಲೆಕಾಯಿ',
        'Soybean': 'ಸೋಯಾ ಬೀನ್', 'Sunflower': 'ಸೂರ್ಯಕಾಂತಿ', 'Black Gram (Urad)': 'ಉದ್ದು',
        'Bengal Gram (Chana)': 'ಕಡಲೆ ಬೇಳೆ', 'Red Gram (Tur Dal)': 'ತೊಗರಿ ಬೇಳೆ', 'Green Gram (Moong)': 'ಹೆಸರುಕಾಳು',
    },
};
